### ISSUE TITLE
Permission denied trying to write on SI.out

### ISSUE THREAD

**Issue by pherrymason** [gmassei/VectorMCDA#1]
I'm on Mac 10.11.5 El capitan and using this command through QGIS3.

Running the command `geoWeightedSum` I get the following error:

```
PermissionError: [Errno 13] Permission denied: 'SI.out' 
Traceback (most recent call last):
  File "/Users/raulferras/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/VectorMCDA/geoWeightedSum.py", line 319, in elaborate
    matrix=self.getAttributeMatrix()
  File "/Users/raulferras/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/VectorMCDA/geoWeightedSum.py", line 401, in getAttributeMatrix
    np.savetxt("SI.out",matrix, header=criteriaLabel, delimiter=';',fmt='%1.4f')
  File "", line 6, in savetxt
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/lib/npyio.py", line 1364, in savetxt
    open(fname, 'wt').close()
PermissionError: [Errno 13] Permission denied: 'SI.out'
````

I've tried modifying the python script and set an absolute path to `SI.out` to my home dir but did not work, it throws the same error.

I've also tried the above, but creating the file myself and setting permissions 777 with chmod, also did not work.

Any ideas?

**Comment by gmassei** [comment]
I've upload a new version of VectorMCDA (3.0.0). It's still experimental, but it should  solve the problem that you have reported. Once the versione will be approved, please upgrade  and try.
I' hope you can close the issue.
Best regurads
Gianluca Massei

**Comment by pherrymason** [comment]
Will try, thanks

**Comment by gmassei** [comment]
If you're agree, I'll close the issue.
